DIGPES/Controllers/PesquisaController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using DIGPES.Models;
using DIGPES.ViewModel;
using System.Linq;

namespace DIGPES.Controllers
{
    public class PesquisaController : Controller
    {
        private readonly DIGPESContext _context;

        public PesquisaController(DIGPESContext context)
        {
            _context = context;
        }

       
        public IActionResult Sumarizado()
        {
            var listaOs = _context.PesquisaModel.ToListAsync();
            var vm = new QuestionarioVM();
            var listaquestionario = new List<QuestionarioVM>();
            for (int i = 0; i < listaOs.Result.Count; i++)
            {
                vm = DadosManipulados(listaOs.Result[i]);
                listaquestionario.Add(vm);
            }
            return View(listaquestionario);                   
        }

   
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            var pesquisaModel = await _context.PesquisaModel
                .SingleOrDefaultAsync(m => m.id == Id);
            if (pesquisaModel == null)
            {
                return NotFound();
            }
                        

            QuestionarioVM questionarioVm = new QuestionarioVM { Pesquisa = pesquisaModel };

            questionarioVm.Id = Id.Value;

            questionarioVm.QuestaoA = new List<Categoria>() { new Categoria { Id = 1, Valor = "Sim" }, new Categoria { Id = 2, Valor = "Não" } };
            questionarioVm.QuestaoB = new List<Categoria>() { new Categoria { Id = 1, Valor = "Instalação do produto" }, new Categoria { Id = 2, Valor = "Orientações sobre o uso" }, new Categoria { Id = 3, Valor = "Conserto do produto" } };
            questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 1, Valor = "Lista telefônica" }, new Categoria { Id = 2, Valor = "Viu na rua" }, new Categoria { Id = 3, Valor = "Linha 0800" }, new Categoria { Id = 4, Valor = "Manual do produto" }, new Categoria { Id = 5, Valor = "Indicação de conhecidos" } };
            questionarioVm.QuestaoD = new List<Categoria>()
            {
                new Categoria { Id = 1, Valor = "Muito Satisfeito", Checado =false },
                new Categoria { Id = 2, Valor = "Satisfeito", Checado = false },
                new Categoria { Id = 3, Valor = "Razoavelmente satisfeito", Checado =false } ,
                new Categoria { Id = 4, Valor = "Insatisfeito", Checado =false },
                new Categoria { Id = 5, Valor = "Muito insatisfeito", Checado =false }
            };
            questionarioVm.QuestaoE = new List<Categoria>() { new Categoria { Id = 1, Valor = "Sim" }, new Categoria { Id = 2, Valor = "Não" } };
            

            return View(questionarioVm);
        }

      
        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PesquisaModel pesquisaModel)
        {
           
            if (ModelState.IsValid)
            {
                _context.Add(pesquisaModel);
                await _context.SaveChangesAsync();

               var  id = pesquisaModel.id;
                return RedirectToAction("Details", new { id });

            }        

            return View(pesquisaModel);
        }


    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Atualizar(PesquisaModel questionarioVM)
        {            
            if (ModelState.IsValid)
            {
                _context.Update(questionarioVM);                
                await _context.SaveChangesAsync();              
                return RedirectToAction("Sumarizado");
            }

            return View(questionarioVM);
        }

        public IActionResult Grafico()
        {
            var listaOs = _context.PesquisaModel.ToListAsync();


            return View();
        }
        

        private QuestionarioVM DadosManipulados(PesquisaModel pesquisa)
        {
            var questionarioVm = new QuestionarioVM();

            questionarioVm.OS = pesquisa.OS;
            questionarioVm.CodigoProduto = pesquisa.CodigoProduto;
            questionarioVm.Nome = pesquisa.Nome;
            questionarioVm.Data = pesquisa.Data;


            if (pesquisa.QuestaoA.HasValue)
            {
                if ((pesquisa.QuestaoA.Value == 1))
                {
                    questionarioVm.QuestaoA = new List<Categoria>() { new Categoria { Id = 1, Valor = "Sim" } };
                }
                else
                {
                    questionarioVm.QuestaoA = new List<Categoria>() { new Categoria { Id = 1, Valor = "Não" } };
                }
            }


            switch (pesquisa.QuestaoB)
            {
                case 1:
                    questionarioVm.QuestaoB = new List<Categoria>() { new Categoria { Id = 1, Valor = "Instalação do produto" } };
                    break;
                case 2:
                    questionarioVm.QuestaoB = new List<Categoria>() { new Categoria { Id = 2, Valor = "Orientações sobre o uso" } };
                    break;
                case 3:
                    questionarioVm.QuestaoB = new List<Categoria>() { new Categoria { Id = 3, Valor = "Conserto do produto" } };
                    break;
                default:
                    break;
            }


            switch (pesquisa.QuestaoC)
            {
                case 1:
                    questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 1, Valor = "Lista telefônica" } };
                    break;
                case 2:
                    questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 2, Valor = "Viu na rua" } };
                    break;
                case 3:
                    questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 3, Valor = "Linha 0800" } };
                    break;
                case 4:
                    questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 4, Valor = "Manual do produto" } };
                    break;
                case 5:
                    questionarioVm.QuestaoC = new List<Categoria>() { new Categoria { Id = 5, Valor = "Indicação de conhecido" } };
                    break;
                default:
                    break;
            }
            
            // var valorcheckbox = pesquisa.QuestaoD.Split(",");
            // foreach (var item in pesquisa.QuestaoD)
            {
                switch (pesquisa.QuestaoD)
                {
                    case 1:
                        questionarioVm.QuestaoD = new List<Categoria>() { new Categoria { Id = 1, Valor = "Muito Satisfeito" } };
                        break;
                    case 2:
                        questionarioVm.QuestaoD = new List<Categoria>() { new Categoria { Id = 2, Valor = "Satisfeito" } };
                        break;
                    case 3:
                        questionarioVm.QuestaoD = new List<Categoria>() { new Categoria { Id = 3, Valor = "Razoavelmente satisfeito" } };
                        break;
                    case 4:
                        questionarioVm.QuestaoD = new List<Categoria>() { new Categoria { Id = 3, Valor = "Insatisfeito" } };
                        break;

                    case 5:
                        questionarioVm.QuestaoD = new List<Categoria>() { new Categoria { Id = 3, Valor = "Muito insatisfeito" } };
                        break;
                    default:
                        break;
                }
            }


            questionarioVm.Justificativa = pesquisa.Justificativa;


            if (pesquisa.QuestaoE.HasValue)
            {
                if ((pesquisa.QuestaoE.Value == 1))
                {
                    questionarioVm.QuestaoE = new List<Categoria>() { new Categoria { Id = 1, Valor = "Sim" } };
                }
                else
                {
                    questionarioVm.QuestaoE = new List<Categoria>() { new Categoria { Id = 1, Valor = "Não" } };
                }
            }      


            return questionarioVm;

        }
             
        public JsonResult GraficoA()
        {            
            var Total = _context.PesquisaModel.ToArray().Length;
            var sumQuestaoAS = _context.PesquisaModel.Where(x => x.QuestaoA == 1).Sum(x => x.QuestaoA.Value);

            var total = new List<SomaGraficoModel>
            {
                new SomaGraficoModel { Resposta = "Sim", Valor = sumQuestaoAS },
                new SomaGraficoModel { Resposta = "Nao", Valor = Total - sumQuestaoAS }
            };

            return Json(total);
        }

        public IActionResult Index()
        {
            return View();
        }


    }
}

DIGPES/Views/Pesquisa/Create.cshtml
@model DIGPES.Models.PesquisaModel

@{
    ViewData["Title"] = "Cadastro";
}

<h2>Create</h2>

<h4>PesquisaModel</h4>
<hr />

<section id="pagina1">
    <div class="container">      
            <form id="contact" asp-action="Create" asp-controller="Pesquisa" method="POST" role="form" asp-antiforgery="true">
            <h3>PESQUISA DE SATISFAÇÃO</h3>
            <h4>DIGPES</h4>
            <fieldset>                
                <input asp-for="OS" placeholder="Ordem de Serviço" class="with-text" type="number" tabindex="1" required autofocus>
            </fieldset>
            <fieldset>
                <input asp-for="CodigoProduto" placeholder="Produto" type="text"  tabindex="2" required>
            </fieldset>
            <fieldset>
                <input asp-for="Nome" placeholder="Nome (Obrigatório)" id="Nome" type="text" tabindex="3" required>
            </fieldset>
            <fieldset>
                <input asp-for="Data"  placeholder="Data" type="date" class="tamanhodata" id="Data" tabindex="4" required>
            </fieldset>
            <fieldset>
                <button name="submit" type="submit" id="submit-1" data-submit=".">Próximo</button>
            </fieldset>
        </form>

    </div>
</section>

DIGPES/Views/Pesquisa/Details.cshtml
@model DIGPES.ViewModel.QuestionarioVM

@{
    ViewData["Title"] = "Details";

    var id = @Model.Pesquisa.id;
    @Model.Id = id;
    var nome = Model.Pesquisa.Nome;
    @Model.Nome = nome;
    var produto = Model.Pesquisa.CodigoProduto;
    @Model.CodigoProduto = produto;
    var data = Model.Pesquisa.Data;
    Model.Data = Model.Pesquisa.Data;
    var OS = Model.Pesquisa.OS;
    Model.OS = OS;
}

<h2>Detalhes</h2>

<div class="container-center cor-segundo-box">

    <form id="contact1" asp-action="Atualizar" asp-controller="Pesquisa" method="POST" role="form" asp-antiforgery="true">

        <div>
            <h4>PesquisaModel</h4>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            OS
                        </th>
                        <th>
                            Código do Produto
                        </th>
                        <th>
                            Nome
                        </th>
                        <th>
                            Data
                        </th>
                        <th>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @Model.Pesquisa.id
                        </td>
                        <td>
                            @Model.Pesquisa.CodigoProduto
                        </td>
                        <td>
                            @Model.Pesquisa.Nome
                        </td>
                        <td>
                            @Model.Pesquisa.Data.ToString("dd/MM/yyyy")
                        </td>
                        <td></td>
                    </tr>

                </tbody>
            </table>

            <hr />

            

            <div class="form-group" id="GrupoA">
                <h5>A)	O Sr(a) ainda possui o produto mencionado acima ?</h5>

                <input asp-for="@Model.QuestaoA" value="@Model.QuestaoA[0].Id" type="radio" id="QuestaoAS" />
                <label asp-for="@Model.QuestaoA[0].Id">@Model.QuestaoA[0].Valor</label>

                <input asp-for="@Model.QuestaoA" value="@Model.QuestaoA[1].Id" type="radio" id="QuestaoAN" />
                <label asp-for="@Model.QuestaoA[1].Id">@Model.QuestaoA[1].Valor</label>

                <input asp-for="@Model.QuestaoA[0].Id" type="hidden" />
            </div>


            <div class="form-group" id="GrupoB">
                <h5>B)	O Sr(a) ainda possui o produto mencionado acima ?</h5>

                <input asp-for="@Model.QuestaoB" value="@Model.QuestaoB[0].Id" type="radio" />
                <label asp-for="@Model.QuestaoB[0].Id">@Model.QuestaoB[0].Valor</label>

                <input asp-for="@Model.QuestaoB" value="@Model.QuestaoB[1].Id" type="radio" />
                <label asp-for="@Model.QuestaoB[1].Id">@Model.QuestaoB[1].Valor</label>

                <input asp-for="@Model.QuestaoB[0].Id" type="hidden" />
            </div>

            <div class="form-group" id="GrupoC">
                <h5>C)Para que tipo de serviço você solicitou assistência técnica:</h5>

                <input asp-for="@Model.QuestaoC" value="@Model.QuestaoC[0].Id" type="radio" />
                <label asp-for="@Model.QuestaoC[0].Id">@Model.QuestaoC[0].Valor</label>

                <input asp-for="@Model.QuestaoC" value="@Model.QuestaoC[1].Id" type="radio" />
                <label asp-for="@Model.QuestaoC[1].Id">@Model.QuestaoC[1].Valor</label>

                <input asp-for="@Model.QuestaoC[0].Id" type="hidden" />
            </div>


            <div class="form-group" id="GrupoD">
                <h5>
                    D)	Como você localizou o telefone do Serviço Autorizado?  (Assinale quantas quiser)
                </h5>

                @foreach (var item in @Model.QuestaoD)
            {
                    <input asp-for="@item.Checado" type="checkbox" />
                    <label asp-for="@item.Id">@item.Valor</label>
                    <input asp-for="@item.Id" type="hidden" class="checado" />
                    <input asp-for="@item.Valor" type="hidden" class="checado" />
                    <br />
        }
            </div>


            <div class="form-group" id="Justi">
                <h5>D)	Baseado no atendimento recebido pelo pessoal do Serviço Autorizado, o Sr(a) diria que está:</h5>

                <label>Justificativa </label>

                <input asp-for="@Model.Justificativa" value="@Model.Justificativa" type="text" id="justifique" />
                <input asp-for="@Model.Justificativa" type="hidden" />
            </div>

            <div class="form-group" id="GrupoE">
                <h5>E)Você recomendaria os nossos produtos para alguém </h5>

                <input asp-for="@Model.QuestaoE" value="@Model.QuestaoE[0].Id" type="radio" />
                <label asp-for="@Model.QuestaoE[0].Id">@Model.QuestaoE[0].Valor</label>

                <input asp-for="@Model.QuestaoE" value="@Model.QuestaoE[1].Id" type="radio" />
                <label asp-for="@Model.QuestaoE[1].Id">@Model.QuestaoE[1].Valor</label>

                <input asp-for="@Model.QuestaoE[0].Id" type="hidden" />
            </div>



        </div>

        <div>
            <input asp-for="@Model.Id" type="hidden" />
            <input asp-for="@Model.Nome" type="hidden" />
            <input asp-for="@Model.CodigoProduto" type="hidden" />
            <input asp-for="@Model.OS" type="hidden" />

            <input asp-for="@Model.Data" type="hidden" />

            <button name="submit" type="submit" id="submit-1" data-submit="...">Próximo</button>
            <a asp-action="Index">Back to List</a>
        </div>
    </form>

</div>

DIGPES/Views/Pesquisa/Index.cshtml
<script type="text/javascript" src="https://www.google.com/jsapi" async></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js" async></script>

<script type="text/javascript">
    google.load("visualization", "1", { packages: ["corechart"] });
</script>


<br />
<br />
<div class="container container-center">
    <div id="divgrafico">
    </div>

    <hr />
    <a asp-area="" class="btn btn-info" asp-controller="Pesquisa" asp-action="Create">Início</a>
</div>





<script>
    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax(
            {
                url: '@Url.Action("GraficoA", "Pesquisa")',
                dataType: "json",
                type: "GET",
                error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
                },
                success: function (data) {
                PopulaGrafico(data);
                return false;
                }

                });
                return false;
                }


    function PopulaGrafico(dadosentrada) {

                    var data = new google.visualization.DataTable();

                    data.addColumn('string', 'resposta');
                    data.addColumn('number', 'valor');

                    for (var i = 0; i < dadosentrada.length; i++) {
                        data.addRow([dadosentrada[i].resposta, dadosentrada[i].valor]);
                    }

                    var chart = new google.visualization.PieChart(document.getElementById('divgrafico'));

                    chart.draw(data,
                        {
                            title: "Gráfico sobre o total de respostas",                            
                            fontsize: "22px",
                            chartArea: { width: '85%' },
                        });
                };
</script>

DIGPES/Views/Pesquisa/Sumarizado.cshtml
@model IEnumerable<DIGPES.ViewModel.QuestionarioVM>


@{
    ViewData["Title"] = "Tabela de respostas";
}

<h2>Sumarizado</h2>

<div id="sumarizado" class="sumarizado">   
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.OS)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CodigoProduto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Data)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestaoA)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestaoB)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestaoC)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestaoD)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Justificativa)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.QuestaoE)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.OS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodigoProduto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Data)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestaoA[0].Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestaoB[0].Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestaoC[0].Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestaoD[0].Valor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Justificativa)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.QuestaoE[0].Valor)
                    </td>

                </tr>
            }
        </tbody>
    </table>

    <a asp-area="" class="btn btn-info" asp-controller="Pesquisa" asp-action="Index">Gráfico de respostas</a> 

</div>